language: python
python:
  - 2.7
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
script:
  ./runtests.sh
notifications:
  email: false
  slack:
    - hasgeek:HDCoMDj3T4ICB59qFFVorCG8
    - friendsofhasgeek:3bLViYSzhfaThJovFYCVD3fX
