language: python
python:
  - 2.6
  - 2.7
install:
  pip install -r requirements.txt --use-mirrors
script:
  python runtests.py
notifications:
  email: false
  slack: hasgeek:HDCoMDj3T4ICB59qFFVorCG8
  slack: friendsofhasgeek:3bLViYSzhfaThJovFYCVD3fX
